import { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { GeoData } from 'types'
import Form from 'components/Form'
import InfoBox from 'components/InfoBox'
import dynamic from 'next/dynamic'
import { getGeoData } from 'utils/getGeoData'
const Map = dynamic(() => import('components/Map'), { ssr: false })
import styles from 'styles/Home.module.css'

const Home: NextPage = () => {
  const [data, setData] = useState<GeoData>()

  useEffect(() => {
    getGeoData('').then((data) => setData(data))
  }, [])

  if (!data) return null

  return (
    <>
      <Head>
        <title>IP Address Tracker</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div className={styles.input_wrapper}>
          <h1>IP Address Tracker</h1>
          <Form setData={setData} />
        </div>
        <InfoBox {...data} />
        <Map {...data} />
      </main>
    </>
  )
}

export default Home
